### ISSUE TITLE
Can't bind a class to a custom node.

### ISSUE THREAD

**Issue by raditha** [eternita/workflow#10]
When binding the class to a custom node the "Available blocks" doesn't show any classes which were created. 
![image](https://user-images.githubusercontent.com/8841975/29569042-f33dab20-876f-11e7-9f29-02740b7ad7a4.png)

**Comment by dpavlikovskiy** [comment]
@raditha  Can you attach zip of your project?

**Comment by raditha** [comment]
Sure.I am using JDK 1.7 with neuro studio 0.9.The project is attached.
[jwtTest3.zip](https://github.com/eternita/workflow/files/1244061/jwtTest3.zip)

**Comment by dpavlikovskiy** [comment]
@raditha please download latest (2.0.1) studio from http://static.neuro4j.org/download/studio/ (0.9 is very old version). Also it requires java8... Let me know if it solves your problem
 
<img width="1146" alt="screen shot 2017-08-22 at 11 21 37 pm" src="https://user-images.githubusercontent.com/4432229/29600041-ca0b9282-8790-11e7-8b16-9c8f609e64ef.png">

**Comment by raditha** [comment]
@dpavlikovskiy Downloading the latest and upgrading to java 1.8 solved the issue. But when i'm trying to run the example provided in the documentation the following exception occurs.


`INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ WorkflowExample ---
15:23:21.744 [org.neuro4j.workflow.tutorial.App.main()] DEBUG org.neuro4j.workflow.node.WorkflowProcessor - Loading flow: FlowParameter [flowName=org.neuro4j.workflow.tutorial.HelloFlow, flowPackage=org.neuro4j.workflow.tutorial, startNode=Start]
15:23:21.750 [org.neuro4j.workflow.tutorial.App.main()] DEBUG org.neuro4j.workflow.cache.ConcurrentMapWorkflowCache - Loading to cache: org.neuro4j.workflow.tutorial.HelloFlow
[WARNING]
java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replaceAll(String.java:2223)
        at org.neuro4j.workflow.loader.URLWorkflowLoader.normalize(URLWorkflowLoader.java:80)
        at org.neuro4j.workflow.loader.ClasspathWorkflowLoader.getResource(ClasspathWorkflowLoader.java:37)
        at org.neuro4j.workflow.loader.URLWorkflowLoader.load(URLWorkflowLoader.java:46)
        at org.neuro4j.workflow.loader.RemoteWorkflowLoader.load(RemoteWorkflowLoader.java:83)
        at org.neuro4j.workflow.cache.ConcurrentMapWorkflowCache$WorkflowProxy.get(ConcurrentMapWorkflowCache.java:91)
        at org.neuro4j.workflow.cache.ConcurrentMapWorkflowCache.get(ConcurrentMapWorkflowCache.java:61)
        at org.neuro4j.workflow.node.WorkflowProcessor.loadWorkflow(WorkflowProcessor.java:232)
        at org.neuro4j.workflow.node.WorkflowProcessor.execute(WorkflowProcessor.java:93)
        at org.neuro4j.workflow.common.WorkflowEngine.execute(WorkflowEngine.java:95)
        at org.neuro4j.workflow.tutorial.App.main(App.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by dpavlikovskiy** [comment]
@raditha What example did you try?  `WorkflowExample` from https://github.com/eternita/workflow/tree/master/tutorials/

**Comment by raditha** [comment]
@dpavlikovskiy  I tried the [workflowExample](https://github.com/eternita/workflow/tree/master/tutorials/WorkflowExample) from the tutorials.

**Comment by dpavlikovskiy** [comment]
@raditha I have updated version to 3.4.1 in tutorials
https://github.com/eternita/workflow/commit/6e212d21ba8a38759d7030dc3493df70f76284e0#diff-d5c7848720b108dc67ff93368df1502eR13
Please try again and thanks for reporting an issue

**Comment by raditha** [comment]
@dpavlikovskiy  Now it works as expected after the update.Thank you for the prompt response and support.
